# Generated by Django 5.1.7 on 2025-10-14 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_vnpay_bank_code_order_vnpay_card_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khu vực')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Phí cơ bản')),
                ('additional_fee_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Phí thêm mỗi km')),
                ('estimated_delivery_hours', models.IntegerField(default=24, verbose_name='Thời gian giao dự kiến (giờ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('districts', models.TextField(help_text='Danh sách quận/huyện, mỗi dòng một quận', verbose_name='Danh sách quận/huyện')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khu vực giao hàng',
                'verbose_name_plural': 'Khu vực giao hàng',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('vehicle_type', models.CharField(choices=[('motorbike', 'Xe máy'), ('car', 'Ô tô'), ('bicycle', 'Xe đạp'), ('truck', 'Xe tải')], default='motorbike', max_length=20, verbose_name='Loại phương tiện')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, verbose_name='Biển số xe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Đánh giá')),
                ('total_deliveries', models.IntegerField(default=0, verbose_name='Tổng số đơn đã giao')),
                ('successful_deliveries', models.IntegerField(default=0, verbose_name='Số đơn giao thành công')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_person', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Nhân viên giao hàng',
                'verbose_name_plural': 'Nhân viên giao hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ phân công'), ('assigned', 'Đã phân công'), ('picked_up', 'Đã lấy hàng'), ('in_transit', 'Đang giao'), ('delivered', 'Đã giao'), ('failed', 'Giao thất bại'), ('returned', 'Đã hoàn trả')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('pickup_address', models.TextField(verbose_name='Địa chỉ lấy hàng')),
                ('delivery_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('recipient_phone', models.CharField(max_length=15, verbose_name='SĐT người nhận')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian phân công')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian lấy hàng')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao dự kiến')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian giao thực tế')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Lý do thất bại')),
                ('delivery_proof_image', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/', verbose_name='Ảnh xác nhận giao hàng')),
                ('customer_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Đánh giá của khách hàng')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='Phản hồi của khách hàng')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ hiện tại')),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ hiện tại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='Đơn hàng')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='delivery.deliveryperson', verbose_name='Nhân viên giao hàng')),
            ],
            options={
                'verbose_name': 'Giao hàng',
                'verbose_name_plural': 'Giao hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='Trạng thái')),
                ('message', models.TextField(verbose_name='Thông điệp')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='Tên địa điểm')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='delivery_tracking/', verbose_name='Hình ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='delivery.delivery', verbose_name='Giao hàng')),
            ],
            options={
                'verbose_name': 'Theo dõi giao hàng',
                'verbose_name_plural': 'Theo dõi giao hàng',
                'ordering': ['-created_at'],
            },
        ),
    ]
