# Generated by Django 5.1.7 on 2025-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vnpay_bank_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mã ngân hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='vnpay_card_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Loại thẻ'),
        ),
        migrations.AddField(
            model_name='order',
            name='vnpay_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thanh toán VNPay'),
        ),
        migrations.AddField(
            model_name='order',
            name='vnpay_response_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Mã phản hồi'),
        ),
        migrations.AddField(
            model_name='order',
            name='vnpay_transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch VNPay'),
        ),
        migrations.AddField(
            model_name='order',
            name='vnpay_transaction_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mã GD tại VNPAY'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('vnpay', 'Thanh toán VNPay'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('credit_card', 'Thẻ tín dụng'), ('e_wallet', 'Ví điện tử')], default='cod', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
    ]
