# Generated by Django 5.1.7 on 2025-10-21 08:52

from django.db import migrations, models
from django.utils.text import slugify
import uuid


def generate_category_slugs(apps, schema_editor):
    """Generate unique slugs for existing categories"""
    Category = apps.get_model('products', 'Category')
    for category in Category.objects.all():
        base_slug = slugify(category.name)
        # Remove hyphens for better Vietnamese support
        base_slug = base_slug.replace('-', '')
        if not base_slug:  # If slugify returns empty (all Vietnamese)
            base_slug = f"category-{uuid.uuid4().hex[:8]}"
        
        # Ensure uniqueness
        slug = base_slug
        counter = 1
        while Category.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        
        category.slug = slug
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_alter_discount_options_and_more'),
    ]

    operations = [
        # First add the field as nullable
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Đường dẫn'),
        ),
        # Generate slugs for existing data
        migrations.RunPython(generate_category_slugs, reverse_code=migrations.RunPython.noop),
        # Make it unique and non-null
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Đường dẫn'),
        ),
    ]
