# Generated by Django 5.1.7 on 2025-10-24 01:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Đánh giá từ 1 đến 5 sao', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('comment', models.TextField(verbose_name='Nội dung đánh giá')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Đã từng mua hàng')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Đã duyệt')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Hiển thị nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đánh giá cửa hàng',
                'verbose_name_plural': 'Đánh giá cửa hàng',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_shop_review_per_user')],
            },
        ),
    ]
