# Generated by Django 5.1.7 on 2025-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_shopreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hủy đăng ký')),
            ],
            options={
                'verbose_name': 'Đăng ký nhận tin',
                'verbose_name_plural': 'Đăng ký nhận tin',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
